---
- name: Clone repository
  git:
    repo: 'https://github.com/willianpaixao/dotfiles.git'
    dest: /home/willian/dev/dotfiles
    version: v0.3
  become: true
  become_user: willian
  tags: dotfiles

- name: Create symbolic links
  file:
    src: '/home/willian/dev/dotfiles/{{ item.src }}'
    path: '/home/willian/{{ item.path }}'
    state: link
    force: yes
  become: true
  become_user: willian
  with_items:
          - { src: 'bash_aliases', path: '.bash_aliases' }
          - { src: 'bash_logout', path: '.bash_logout' }
          - { src: 'bashrc', path: '.bashrc' }
          - { src: 'gitconfig', path: '.gitconfig' }
          - { src: 'tmux.conf', path: '.tmux.conf' }
          - { src: 'vimrc', path: '.vimrc' }
  tags: dotfiles
